apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redisbank-redb
  namespace: redis-apps
spec:
  modulesList:
    - name: search
      version: 2.2.6
    - name: timeseries
      version: 1.4.13
  redisEnterpriseCluster:
    name: rec
  shardCount: 2
  shardsPlacement: dense
  databasePort: 12869
  databaseSecretName: redisbank-auth
  memorySize: 1GB
